### ISSUE TITLE
feature request: unenrol person from a course if original course completion is removed

### ISSUE THREAD

**Issue by jarvil1** [ewallah/moodle-enrol_coursecompleted#11]
Hello,

If I roll person to course 2 after completing course 1 and then I remove "course completed" mark from the person on course 1 I would like to see an feature that unenrols them from course 2.

**Comment by ewallah** [comment]
Hello Urpokarhu1,

I do not fully understand your request: "If you remove the course completed mark from the person".  How do you do this? The student got the completion mark because all requirements were met, so the student will be marked automatically complete again after the next cron job. 

R

**Comment by jarvil1** [comment]
Hello,

You can remove course completion -mark (from course completion -report) from a student f.ex by changing course completion criteria for course 1 f.ex adding more activities to complete before the person is rewarded course completion mark.

There are also plugins that deletes users course completion marks, these are used for coursesta that are required to be rerecompleted f.ex once a year

**Comment by ewallah** [comment]
Hello,

This seems unfair to me, the student got the completion and the enrolment because all old requirements were met. All new enrolments will be based upon the new criteria.

I compare this behaviour with a certificate: if you give a certificate when a student passes a quiz, you cannot say one month later that this certificate is invalid (the student probably downloaded the certificate and used the document already to apply for a job).

Modifying things in the past is a dangerous and tricky path. Before you know it, a student may go to court because he/she looses access to a course....

**Comment by ewallah** [comment]
Wont fix.
