### ISSUE TITLE
Ability to enroll from not completed course

### ISSUE THREAD

**Issue by okr1m** [ewallah/moodle-enrol_coursecompleted#12]
The request is add to the plugin the ability to auto enrol people who haven't complete a specific course during course validity.

Do you think is possible?

**Comment by ewallah** [comment]
Hello,

With this plugin it is currently impossible to enrol people who have not complete a specific course. The reason is simple - completing a course is a specific moment - not completing a course is a situation, something that can last for years. 

So when would this enrollment be done? At a certain date, when the course end date is reached, when the enrollment period is over, when the course is deleted,...  What has to happen with people who were enrolled by not completing, when they eventually complete the course?

Technically it is possible, but for the moment I see only exponential complexity violating my weakness for the [KISS](https://en.wikipedia.org/wiki/KISS_principle) principle.  Personally I would go for a new enrollment plugin enrol_coursefailure where the logic can be implement more simpler.

R
