### ISSUE TITLE
Send Custom welcome message only on the start date of enrollment

### ISSUE THREAD

**Issue by tammo293** [ewallah/moodle-enrol_coursecompleted#22]
Very useful plugin, well done!
When I activate the "Custom welcome message" function and the "Start date" function, the message to users arrives when they have completed the previous course, not when their enrollment in the current course is activated (on the day I have entered in the "start date").
Thank you for the effort you are putting into this.

**Comment by ewallah** [comment]
Hello Tammo293,

THX for your feedback.

Your request to send the welcome message later could be simply implemented with only 1 line of code. 

But how would I have to handle enrollment start modifications? 
- user completes course
- user is automatically enrolled into a new course
- a welcome message is programmed to be sent at a later date
- some time passes
- teacher changes the enrollment to start one day sooner
- all prepared messages have to be updated to be sent one day sooner ???
- user is enrolled because he used a payment gateway
- the course welcome message has to be deleted for this user ???
- this enrollment method is deleted
- all future welcome messages have to be deleted ???

I avoided future mail problems by sending the welcome messages immediately. Because there is no function or event handling the start of an enrollment in Moodle, I have to prepare the messages when the enrollment is created/modified/deleted.

Do you have a storyboard how these enrollment start modifications could be handled?

R

**Comment by ewallah** [comment]
Hello Tammo293,

You can insert $adhoc->set_next_run_time($enrol->enrolstartdate);  at line 66 of the file classes/observer.php to have the emails sent when the enrolment starts.

As long as I do not have a complete overview of all possible repercussions of this extra line, I wait to implement this core change.

R

**Comment by tammo293** [comment]
Hi @ewallah
Thank you very much for your very quick feedback.
I will try to insert $adhoc->set_next_run_time($enrol->enrolstartdate).
If I encounter any repercussions I will report them to you.

Thanks again.
