### ISSUE TITLE
A question about condition

### ISSUE THREAD

**Issue by Nirzol** [ewallah/moodle-enrol_coursecompleted#3]
Hello

I want to know if it's possible to add one more condition with this plugin .
What I want, it is the possibility when a course is completed , a new one is open but 5 days (or more/ less) after .

For example, a course A completed on 15/01/2019 then the course B will open at 20/01/2019

Other question :  Possible to use this on activity instead course ?

Thanks !

**Comment by ewallah** [comment]
Hello Nirzol,

The idea of relative course start dates is tempting, but not so easy to implement. If not, Moodle would have had this feature a long time ago. Already thought what happens if you change the start date of a course minus one week? Every plugin will have to implement a solution for this change. Enrollment plugins would have to change the enrollment status of people form enrolled to not-yet enrolled, quizzes need to fix their submission dates,... The same with your proposal, while everything looks simple on first thought, the reality is much harder. Let's wait for the Moodle solution for relative course start dates.

The plugin is open source, so feel free to implement your changes. But in your case I would opt for a far simpler solution: add an event to your theme that does the job: if a user is enrolled in a course by the enrol_coursecompleted plugin, add 5 days to the enrollment start date.

Your second question is easier to implement. I already have a pretty good idea how to make a enrol_activitycompleted plugin. However none of the Moodle installations I manage, needs such a feature. As long as there is no need nor budget,....

Greetings,
R

**Comment by Nirzol** [comment]
Hi !
Thanks a lot for your complete reply ! 
I will see if I can create this feature.
