### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by leevigraham** [ewallah/moodle-enrol_coursecompleted#4]
Is there anyway to know from the repo which release is which commit?

**Comment by ewallah** [comment]
Hello Leevi,

sorry, but in this repo there is no easy way to know in which release is which commit. Partly laziness, partly because this is the "public"version of a private closed source plugin.

P.S. The available versions can be viewed at https://moodle.org/plugins/pluginversions.php?plugin=enrol_coursecompleted

**Comment by leevigraham** [comment]
Ah ok… so using submodules is out of the question for this plugin.
