### ISSUE TITLE
Enrolment on completion of completing an entrance test course and payment completed?

### ISSUE THREAD

**Issue by zenny** [ewallah/moodle-enrol_coursecompleted#40]
Hi, 

Thanks for sharing something that I have been searching for. Yet I have two conditions for enrolment:

1. Every student has to complete a course related to the competency with an online exam before they are enrolled. The course has a minimal fee, too.
2. Enrollment to the main program is only allowed only after successfully completing the 1 and then payment for the main course.
3. Once the person completes the second course and pays, then will be enrolled to the third one, and so on.

I appreciate if anyone could explain to achieve the outcomes as above using this plugin.

Cheers,
/zenny

**Comment by ewallah** [comment]
Hello @zenny,

This will not be simple to implement because enrollment in Moodle is using an OR restriction : or you are manually enrolled, or you payed using PayPal, or you payed using another payment gateway, or you completed a course and therefore you have access to the course, ....  It cannot be that a student has to pay twice when 2 payment methods are enabled.

You want to implement an AND situation: the user completed a course AND the user has payed.

You could create extra courses for payment only (a single activity page with activity and course completion enabled only showing a link to your next course). Next you can add this payment course as a requirement to complete your competency course.  On that moment you can add this plugin to the second course and have the completion of course 1 as a parameter.

What will happen:  A user visits course 1, but he/she cannot complete this course as long as the payment course is not completed.  The moment a user pays, the payment course is marked complete. As a result the first course is also marked complete, and finally the user is automatically enrolled into the second course,

This is not an ideal scenario, so I would opt for a mod_fee plugin to let a payment happen inside a course. This module could support activity completion and be part of the course completion (mark an activity complete when a user pays). This way a course can be open for everybody and chapters can remain hidden until the mod_fee activity is marked complete.....

**Comment by zenny** [comment]
> Hello @zenny,
> 
> This will not be simple to implement because enrollment in Moodle is using an OR restriction : or you are manually enrolled, or you payed using PayPal, or you payed using another payment gateway, or you completed a course and therefore you have access to the course, .... It cannot be that a student has to pay twice when 2 payment methods are enabled.
> 
> You want to implement an AND situation: the user completed a course AND the user has payed.
> 
> You could create extra courses for payment only (a single activity page with activity and course completion enabled only showing a link to your next course). Next you can add this payment course as a requirement to complete your competency course. On that moment you can add this plugin to the second course and have the completion of course 1 as a parameter.
> 
> What will happen: A user visits course 1, but he/she cannot complete this course as long as the payment course is not completed. The moment a user pays, the payment course is marked complete. As a result the first course is also marked complete, and finally the user is automatically enrolled into the second course,
> 
> This is not an ideal scenario, so I would opt for a mod_fee plugin to let a payment happen inside a course. This module could support activity completion and be part of the course completion (mark an activity complete when a user pays). This way a course can be open for everybody and chapters can remain hidden until the mod_fee activity is marked complete.....

@ewallah and @rdebleu thanks for your explanation.

The real situation is like a student has to pay first and complete a first course to prove competency in specialized field as the basic requirement to enrol into the second course on payment.

Thus,

1. In the first course the student pays first and gets enrolled`*`.
2. Once (1) is completed will be automatically invited to join to the second course, once payment clears.

`*` No. 1 above is similar to the competency assessment tests similar to GRE, TOEFL, UKCAT or other requirements in order to prove eligibility to main course in specialized domain.

Cheers,
/zenny

**Comment by ewallah** [comment]
This is a payment issue, not a course completion problem.

We can write a mod_fee plugin that will do exactly what you want (the mod_gwpayments plugin seems not to be maintained any more). In combination with the availability_enrolmentmethod, all your needs would be solved.

**Comment by zenny** [comment]
> This is a payment issue, not a course completion problem.
> 
> We can write a mod_fee plugin that will do exactly what you want (the mod_gwpayments plugin seems not to be maintained any more). In combination with the availability_enrolmentmethod, all your needs would be solved.

@ewallah and @rdebleu, mod_fee plugin you proposed would be an welcoming plugin, indeed. Look forward to. Please ping me if such a plugin is ready. Cheers.

**Comment by ewallah** [comment]
Pleas ping me if you have a budget ready ;-)
