### ISSUE TITLE
enrol_coursecompleted not obeying enrollment duration

### ISSUE THREAD

**Issue by heather-williams** [ewallah/moodle-enrol_coursecompleted#6]
In Moodle 3.5 when setting the enrollment duration for this plug-in in a course, users are not being automatically unenrolled when the enrollment duration is up.

Example: 
• add an instance to course B that enrolls user based on completion of Course A
• set enrollment duration for instance in Course B to 1 hour
• have test user complete Course A and get enrolled into Course B
• wait an hour or more and student is not unenrolled from Course B

This is with the settings set to unenroll the user in the Enrolment expiry action as well.

**Comment by ewallah** [comment]
Hi Heather,

Thanks for the issue report.

I will try to reproduce this behavior and look for a fix ASAP.

**Comment by LilKikr** [comment]
Further to this, it appears that the enrolment expiry is not being recognized because no enrolment period is being created when the user is enrolled.

When a user is enrolled, they are set to active, but start and end are not enabled or set.  So there is nothing to indicate when the user's access to the course should expire.

Example:
I currently have a test user in my system that is showing enrolment created Monday, 11 February 2019, 3:54pm.  Enrolment duration for that particular enrolment instance was set for 1 hour.  The user is still showing active in the course, and can access it from the dashboard.
(This settings are the same as Heather mentioned above)

**Comment by ewallah** [comment]
THX for this extra information.

The latest versions on github should fix this issue.

**Comment by ewallah** [comment]
Fixed.

**Comment by will-bulluck** [comment]
> Fixed.

Is the fixed version on Moodle.org's plugin page?

**Comment by LilKikr** [comment]
A follow-up to Will's comment...  Is the fixed version available from Moodle's plugin page?

**Comment by ewallah** [comment]
If I mention it is fixed, it is fixed on Github AND in the Moodle plugin database.
